export interface ListingsData {
  name: string;
  host: string;
  dates: string;
  duration: string;
  cost: string;
  rating: string;
  like: boolean;
  id: number;
}

export const listings: ListingsData[] = [
  {
    name: "Villa Sicilia 2 views and tranquility in Agaete",
    host: "Pablo",
    dates: "July 8 - 7",
    duration: "1 night",
    cost: "$165",
    rating: "4.95",
    like: false,
    id: 1,
  },
  {
    name: "Entire rental unit hosted by Philipp",
    host: "Phillip",
    dates: "July 10 - 14",
    duration: "4 nights",
    cost: "$375",
    rating: "4.45",
    like: false,
    id: 2,
  },
  {
    name: "Entire villa hosted by Bogdan Gabrie",
    host: "Bogdan",
    dates: "July 14 - 19",
    duration: "5 nights",
    cost: "$765",
    rating: "4.95",
    like: false,
    id: 3,
  },
  {
    name: "Entire home hosted by Axel",
    host: "Axel",
    dates: "July 10 - 27",
    duration: "17 nights",
    cost: "$3,65",
    rating: "4.95",
    like: false,
    id: 4,
  },
  {
    name: "Entire villa hosted by Maria Celeste",
    host: "Maria",
    dates: "July 12 - 17",
    duration: "5 nights",
    cost: "$965",
    rating: "4.95",
    like: false,
    id: 5,
  },
  {
    name: "Entire rental unit hosted by Fernando",
    host: "Fernando",
    dates: "July 12 - 16",
    duration: "4 nights",
    cost: "$905",
    rating: "4.94",
    like: false,
    id: 6,
  },
  {
    name: "Entire villa hosted by Catherine",
    host: "Catherine",
    dates: "July 14 - 31",
    duration: "17 nights",
    cost: "$4,975",
    rating: "4.89",
    like: false,
    id: 7,
  },
  {
    name: "Entire villa hosted by Ana",
    host: "Ana",
    dates: "July 11 - 19",
    duration: "8 nights",
    cost: "$1,440",
    rating: "4.93",
    like: false,
    id: 8,
  },
  {
    name: "Treehouse hosted by Veluvana",
    host: "Veluvana",
    dates: "July 8 - 7",
    duration: "1 night",
    cost: "$456",
    rating: "4.85",
    like: false,
    id: 9,
  },
  {
    name: "Treehouse hosted by Muzi",
    host: "Muzi",
    dates: "July 20 - 24",
    duration: "3 nights",
    cost: "$1,450",
    rating: "4.99",
    like: false,
    id: 10,
  },
  {
    name: "Entire villa hosted by Alberto",
    host: "Alberto",
    dates: "July 18 - 25",
    duration: "7 nights",
    cost: "$1,253",
    rating: "5.0",
    like: false,
    id: 11,
  },
  {
    name: "Entire villa hosted by Domingo",
    host: "Domingo",
    dates: "July 22 - 28",
    duration: "6 nights",
    cost: "$2,292",
    rating: "4.89",
    like: false,
    id: 12,
  },
  {
    name: "Entire villa hosted by Angela",
    host: "Angela",
    dates: "July 14 - 27",
    duration: "4 nights",
    cost: "$3,201",
    rating: "4.95",
    like: false,
    id: 13,
  },
  {
    name: "Luxury stay in Vinišće, Splitsko-dalmatinska županija, Croatia",
    host: "Lisa",
    dates: "July 13 - 16",
    duration: "3 nights",
    cost: "$3,200",
    rating: "4.95",
    like: false,
    id: 14,
  },
  {
    name: "Entire villa hosted by Elen & Andrea",
    host: "Ellen",
    dates: "Sept 9 - 13",
    duration: "4 nights",
    cost: "$1,651",
    rating: "4.95",
    like: false,
    id: 15,
  },
  {
    name: "Entire home hosted by Jennifer",
    host: "Ellen",
    dates: "Aug 12 - 17",
    duration: "5 nights",
    cost: "$1,251",
    rating: "4.9",
    like: false,
    id: 16,
  },
];
